# .github/workflows/ci_workflow.yaml
name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HOME: /home/runner

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install is-verb
        run: npm install is-verb
      - name: DEBUG Print Event
        run: echo ${{ github.event_name }}
      - name: Check Title Format
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '\[(DOCS|FEAT|FIX|STYLE|DEVOPS|REFACTOR|PERF|TEST|CHORE)\] .+$'
          error: 'Your PR title must contain a commit type like "[FIX]".'
          excludeDescription: 'false'  # Check the entire commit message
          excludeTitle: 'false'  # Do not exclude the title
          checkAllCommitMessages: 'false'  # Check only the PR title, assuming it's the first commit
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
      - name: Check Commit Type Format
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|docs|style|refactor|perf|test|chore|devops): .*|^Merge pull request #[0-9]+ from [\w\-]+\/[\w\-].*'
          error: 'Commit message must follow the format "<type>: <description>". Valid types: feat, fix, docs, style, refactor, perf, test, chore.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
        if: ${{ !cancelled() }}
      - name: Check Line Length
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^.{0,80}$'
          error: 'The maximum line length of 80 characters is exceeded.'
          excludeDescription: 'true' # optional: this excludes the description body of a pull request
          excludeTitle: 'true' # optional: this excludes the title of a pull request
          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
        if: ${{ !github.event.pull_request.merged }} && ${{ !cancelled() }}
      - name: Check Verb
        run: .github/scripts/is_verb.sh
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        if: ${{ !github.event.pull_request.merged }} && ${{ !cancelled() }}

  compilation_test:
    name: Compilation Test
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang, clang-12]
    steps:
      - name: Checkout source branch of pull request
        uses: actions/checkout@v4
      - name: Set up test environment
        uses: ./.github/actions/setup
      - name: 🔨 Compile with Makefile
        run: make CXX="${{ matrix.compiler }}"

  combine_compilation_test_results:
    name: Combine Compilation Test Results
    needs: compilation_test
    runs-on: ubuntu-latest
    steps:
      - name: Combine compilation test results
        run: echo "All compilation tests finished"
